plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - HACK
  rubocop:
    enabled: true
    channel: rubocop-0-51
  reek:
    enabled: true
    checks:
      IrresponsibleModule:
        enabled: false
exclude_patterns:
- config/
- db/
- vendor/
- spec/
- test/
