version: "2"
prepare:
  fetch:
    - "https://raw.githubusercontent.com/internetee/style-guide/master/ruby/.rubocop.yml"
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
    channel: eslint-5
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-74
exclude_patterns:
  - "app/models/legacy/"
  - "app/models/version/"
  - "bin/"
  - "config/"
  - "db/"
  - "lib/action_controller/"
  - "lib/core_ext/"
  - "lib/daemons/"
  - "lib/gem_ext/"
  - "lib/tasks/api_log.rake"
  - "lib/tasks/bootstrap.rake"
  - "lib/tasks/db.rake"
  - "lib/tasks/documents.rake"
  - "lib/tasks/import.rake"
  - "lib/tasks/legal_doc.rake"
  - "lib/tasks/whois.rake"
  - "spec/"
  - "test/"
  - "vendor/"
  - "CHANGELOG.md"
