FROM internetee/ruby3_passenger_node14:1.0.19EE
LABEL org.opencontainers.image.source=https://github.com/internetee/registry
ARG RAILS_ENV

ENV RAILS_ENV "$RAILS_ENV"
RUN mkdir -p /opt/webapps/app/tmp/pids
WORKDIR /opt/webapps/app
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle config set without 'development test' && bundle install --jobs 20 --retry 5
COPY . .
RUN mkdir log

EXPOSE 3000