TEST_EMAILS = %w(
  timo.vohmar@internet.ee
  timo.vohmar@eestiinternet.ee
  rene.vahtel@internet.ee
  martin.mettig@internet.ee
  hannes.klausen@internet.ee
  georg.kahest@internet.ee
  norman.aeg@internet.ee
  martti.oigus@internet.ee
  jana.jarve@internet.ee
  martin@gitlab.eu
  priit@gitlab.eu
  info@gitlab.eu
  test@example.com
  test@example.org
  old@example.org
  new@example.org
  old@example.com
  new@example.com
)
