#!/usr/bin/env ruby
results = []
Dir[File.dirname(__FILE__) + '/*_ctl'].each { |f| results << `ruby #{f} #{ARGV.first}` }
results.delete_if { |result| result.blank? }
puts results.join unless results.empty?
