extends: default

rules:
  document-start: disable
  quoted-strings:
    required: only-when-needed
    extra-allowed: ["{|}"]
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
  line-length: disable
  indentation: disable
  new-line-at-end-of-file: disable
  trailing-spaces: disable
  brackets: disable
  colons: disable
  empty-lines: disable
  comments: disable
  braces: disable
  comments-indentation: disable
  commas: disable
