default: &default
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password

test:
  <<: *default
  database: registry_test

demo:
  <<: *default
  database: registry_demo

whois_test:
  <<: *default
  database: registry_whois_test

api_log_test:
  <<: *default
  database: registry_api_log_test
